/**
 * NodeSH Configuration
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

module.exports = {
  // Path to your Express app entry file
  appEntry: 'src/app.js',

  // Directories to load (relative to project root)
  modelsDir: 'src/models',
  servicesDir: 'src/services',
  helpersDir: 'src/helpers',
  configDir: 'src/config',

  // REPL configuration
  prompt: 'express> ',
  useColors: true,
  
  // History file (null for default: ~/.nodesh_history)
  historyFile: null,

  // Additional files to preload
  preload: [],

  // Custom context to add to REPL
  context: {
    // Add any global variables you need in console
    redis: require('./src/config/redis').redis,
    connectDB: require('./src/config/database').connectDB,
  }
};
