/**
 * NodeSH Configuration for Next.js
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

// Load console helpers
const helpers = require('./lib/console');

// Database auto-connects when NodeSH loads

module.exports = {
  // Path to your custom server (if any)
  // Leave empty to let NodeSH auto-detect
  appEntry: null,

  // Directories to load (relative to project root)
  modelsDir: 'src/models',
  servicesDir: 'src/services',
  helpersDir: 'lib',
  configDir: 'config',

  // REPL configuration
  prompt: 'next> ',
  useColors: true,
  
  // History file
  historyFile: null,

  // Additional files to preload (relative to root)
  preload: [],

  // Custom context to add to REPL
  // These will be available as variables in the console
  context: {
    // API calling utilities
    api: helpers.api,
    http: helpers.http,
    fetchApi: helpers.fetchApi,
    
    // Execution utilities
    run: helpers.run,
    batch: helpers.batch,
    
    // Database utilities
    connect: helpers.connect,
    seed: helpers.seed,
    clear: helpers.clear,
    stats: helpers.stats,
    
    // Debugging utilities
    debugApi: helpers.debugApi,
    createRequest: helpers.createRequest,
  }
};
