#!/usr/bin/env node

/**
 * NodeSH CLI
 * Interactive shell for Node.js applications (Express, NestJS, Next.js)
 */
import { program } from 'commander';
import * as path from 'path';
import * as fs from 'fs';
import chalk from 'chalk';
import { ExpressConsole } from './console';
import { loadConfig, generateConfig } from './config';
import { NestJSLoader } from './nestjs-loader';
import { NextJSLoader } from './nextjs-loader';

const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8')
);

interface CLIOptions {
  entry?: string;
  root: string;
  color: boolean;
  prompt?: string;
  init?: boolean;
  env: string;
  nestjs?: boolean;
  nextjs?: boolean;
  express?: boolean;
  yes?: boolean;
}

/**
 * Detect project type and suggest config
 */
function detectProjectType(rootPath: string): 'express' | 'nestjs' | 'nextjs' | 'unknown' {
  // Check for Next.js first (has distinct file structure)
  if (NextJSLoader.isNextJSProject(rootPath)) {
    return 'nextjs';
  }
  
  // Check for NestJS
  if (NestJSLoader.isNestJSProject(rootPath)) {
    return 'nestjs';
  }
  
  // Check for Express indicators
  const expressIndicators = ['app.js', 'server.js', 'index.js', 'app.ts', 'server.ts'];
  for (const file of expressIndicators) {
    if (fs.existsSync(path.join(rootPath, file)) ||
        fs.existsSync(path.join(rootPath, 'src', file))) {
      return 'express';
    }
  }
  
  // Check package.json for dependencies
  const packageJsonPath = path.join(rootPath, 'package.json');
  if (fs.existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      if (deps['next']) return 'nextjs';
      if (deps['@nestjs/core']) return 'nestjs';
      if (deps['express']) return 'express';
    } catch (e) {
      // Ignore
    }
  }
  
  return 'unknown';
}

/**
 * Generate config based on project type
 */
function generateProjectConfig(
  rootPath: string, 
  type: 'express' | 'nestjs' | 'nextjs', 
  force = false
): { created: boolean; path: string; type: string } {
  const configPath = path.join(rootPath, '.nodesh.js');
  
  if (fs.existsSync(configPath) && !force) {
    return { created: false, path: configPath, type };
  }

  let template: string;
  
  if (type === 'nestjs') {
    // Determine if TypeScript
    const isTypeScript = fs.existsSync(path.join(rootPath, 'tsconfig.json')) ||
                        fs.existsSync(path.join(rootPath, 'src', 'main.ts'));
    
    const entryFile = isTypeScript ? 'src/main.ts' : 'src/main.js';
    
    template = `/**
 * NodeSH Configuration for NestJS
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

module.exports = {
  // Path to your NestJS app entry file
  appEntry: '${entryFile}',

  // Directories to load (relative to project root)
  // NestJS projects typically use src/ structure
  modelsDir: 'src',
  servicesDir: 'src',
  helpersDir: 'src/common',
  configDir: 'src/config',

  // REPL configuration
  prompt: 'nest> ',
  useColors: true,
  
  // History file
  historyFile: null,

  // Additional files to preload (relative to root)
  preload: [],

  // Custom context to add to REPL
  context: {
    // Add any global variables you need in console
    // Example: db: require('./src/database')
  }
};
`;
  } else if (type === 'nextjs') {
    template = `/**
 * NodeSH Configuration for Next.js
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

module.exports = {
  // Path to your custom server (if any)
  // Leave empty to let NodeSH auto-detect
  appEntry: null,

  // Directories to load (relative to project root)
  modelsDir: 'models',
  servicesDir: 'services',
  helpersDir: 'lib',
  configDir: 'config',

  // REPL configuration
  prompt: 'next> ',
  useColors: true,
  
  // History file
  historyFile: null,

  // Additional files to preload (relative to root)
  preload: [],

  // Custom context to add to REPL
  context: {
    // Add any global variables you need in console
    // Example: db: require('./lib/db')
  }
};
`;
  } else {
    // Express config
    const hasSrcDir = fs.existsSync(path.join(rootPath, 'src'));
    const isTypeScript = fs.existsSync(path.join(rootPath, 'tsconfig.json'));
    
    const appEntry = hasSrcDir 
      ? (isTypeScript ? 'src/app.ts' : 'src/app.js')
      : (isTypeScript ? 'app.ts' : 'app.js');
    
    const modelsDir = hasSrcDir ? 'src/models' : 'models';
    const servicesDir = hasSrcDir ? 'src/services' : 'services';
    
    template = `/**
 * NodeSH Configuration
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

module.exports = {
  // Path to your Express app entry file
  appEntry: '${appEntry}',

  // Directories to load (relative to project root)
  modelsDir: '${modelsDir}',
  servicesDir: '${servicesDir}',
  helpersDir: '${hasSrcDir ? 'src/helpers' : 'helpers'}',
  configDir: '${hasSrcDir ? 'src/config' : 'config'}',

  // REPL configuration
  prompt: 'express> ',
  useColors: true,
  
  // History file (null for default: ~/.nodesh_history)
  historyFile: null,

  // Additional files to preload
  preload: [],

  // Custom context to add to REPL
  context: {
    // Add any global variables you need in console
    // Example: db: require('./database')
  }
};
`;
  }

  fs.writeFileSync(configPath, template);
  return { created: true, path: configPath, type };
}

program
  .name('nodesh')
  .alias('nsh')
  .alias('eft')
  .description('Interactive shell for Node.js applications (Express, NestJS, Next.js)\n\nAliases: nodesh | nsh | eft')
  .version(packageJson.version)
  .option('-e, --entry <file>', 'Path to app entry file')
  .option('-r, --root <path>', 'Project root directory', process.cwd())
  .option('--no-color', 'Disable colored output')
  .option('-p, --prompt <string>', 'REPL prompt string')
  .option('--init', 'Create a configuration file')
  .option('--env <environment>', 'Set NODE_ENV', 'development')
  .option('--nestjs', 'Force NestJS mode detection')
  .option('--nextjs', 'Force Next.js mode detection')
  .option('--express', 'Force Express mode (skip auto-detection)')
  .option('-y, --yes', 'Auto-generate config if not found (skip prompt)')
  .argument('[projectPath]', 'Project directory (default: current directory)')
  .action(async (projectPath: string | undefined, options: CLIOptions) => {
    // Handle --init flag explicitly
    if (options.init) {
      const projectType = detectProjectType(process.cwd());
      
      if (projectType === 'unknown') {
        console.log(chalk.yellow('Could not detect project type. Creating generic config...'));
        const result = generateConfig(process.cwd());
        if (result.created) {
          console.log(chalk.green(`✓ Created generic configuration: ${result.path}`));
        } else {
          console.log(chalk.yellow(`Configuration already exists: ${result.path}`));
        }
        return;
      }
      
      const result = generateProjectConfig(process.cwd(), projectType, true);
      if (result.created) {
        console.log(chalk.green(`✓ Created ${result.type} configuration: ${result.path}`));
      } else {
        console.log(chalk.yellow(`Configuration already exists: ${result.path}`));
      }
      return;
    }

    // Resolve project path
    const rootPath = projectPath 
      ? path.resolve(projectPath) 
      : path.resolve(options.root);

    // Verify directory exists
    if (!fs.existsSync(rootPath)) {
      console.error(chalk.red(`Error: Directory not found: ${rootPath}`));
      process.exit(1);
    }

    // Check for config file
    const configPath = path.join(rootPath, '.nodesh.js');
    const hasConfig = fs.existsSync(configPath);
    
    // Auto-generate config if not found
    if (!hasConfig) {
      const projectType = detectProjectType(rootPath);
      
      if (projectType !== 'unknown') {
        if (options.yes) {
          // Auto-generate without prompt
          const result = generateProjectConfig(rootPath, projectType);
          console.log(chalk.green(`✓ Auto-generated ${result.type} config: ${result.path}`));
        } else {
          // Ask user
          console.log(chalk.yellow(`No .nodesh.js config found in ${rootPath}`));
          console.log(chalk.cyan(`Detected ${projectType.toUpperCase()} project.`));
          console.log(chalk.gray(`Run with --yes to auto-generate, or --init to create config.`));
          console.log(chalk.gray(`Attempting to start without config...\n`));
        }
      }
    }

    // Set environment
    process.env.NODE_ENV = options.env;

    // Load configuration (will use defaults if no config file)
    const config = loadConfig(rootPath);

    // Override config with CLI options
    if (options.entry) config.appEntry = options.entry;
    if (options.prompt) config.prompt = options.prompt;
    if (options.color === false) config.useColors = false;
    if (options.express) config.forceExpress = true;

    // Change to project directory
    process.chdir(rootPath);

    // Start console
    try {
      const consoleInstance = new ExpressConsole({
        rootPath,
        appEntry: config.appEntry || undefined,
        modelsDir: config.modelsDir,
        servicesDir: config.servicesDir,
        helpersDir: config.helpersDir,
        configDir: config.configDir,
        prompt: config.prompt,
        useColors: config.useColors,
        forceExpress: config.forceExpress
      });
      
      await consoleInstance.start();
    } catch (err) {
      console.error(chalk.red('Failed to start console:'), (err as Error).message);
      process.exit(1);
    }
  });

program.parse();
