/**
 * NodeSH Configuration for NestJS
 * 
 * Auto-generated by nodesh
 * 
 * @see https://github.com/eftech93/nodesh
 */

module.exports = {
  // Path to your NestJS app entry file
  // Use dist/main.js for compiled version (faster, no ts-node issues)
  // Use src/main.ts for direct TypeScript loading (slower, may have module issues)
  appEntry: 'dist/main.js',

  // Directories to load (relative to project root)
  // NestJS projects typically use src/ structure
  modelsDir: 'src',
  servicesDir: 'src',
  helpersDir: 'src/common',
  configDir: 'src/config',

  // REPL configuration
  prompt: 'nest> ',
  useColors: true,
  
  // History file
  historyFile: null,

  // Additional files to preload (relative to root)
  preload: [],

  // Custom context to add to REPL
  context: {
    // Add any global variables you need in console
    // Example: db: require('./src/database')
  }
};
